#!/data/data/com.termux/files/usr/bin/sh
set -e -u

SCRIPTNAME=termux-bluetooth-connect
show_usage () {
    echo "Usage: $SCRIPTNAME [string_uuid]"
    echo "Connect to the given uuid."
    exit 0
}

while getopts :h option
do
    case "$option" in
        h) show_usage;;
        ?) echo "$SCRIPTNAME: illegal option -$OPTARG"; exit 1;
    esac
done
shift $(($OPTIND-1))

if [ $# != 0 ]; then echo "$SCRIPTNAME: too many arguments"; exit 1; fi


CMD="/data/data/com.termux/files/usr/libexec/termux-api BluetoothConnect $PARAMS"

if [ $# = 0 ]; then
    $CMD
else
    echo $@ | $CMD
fi
